### ISSUE TITLE
Please add to readme manual about how to reproduce "7. Combining texture synthesis 'verbs'"

### ISSUE THREAD

**Issue by DenisSergeevitch** [EmbarkStudios/texture-synthesis#13]
In provided manual at the moment hard to find out how to reproduce a result from:
_"7. Combining texture synthesis 'verbs'' section._

Here is a source image:
![nal](https://user-images.githubusercontent.com/2140110/64441039-61d91300-d0cd-11e9-9308-52bba602c145.jpg)

Here is a mask file:
![nal](https://user-images.githubusercontent.com/2140110/64441070-6c93a800-d0cd-11e9-81f3-6cf9e34ceb10.jpg)

And here is a result, which is not even closly nice as the example in readme file :) 
![nal_1](https://user-images.githubusercontent.com/2140110/64441201-b2e90700-d0cd-11e9-8b64-621763666cc4.jpg)

Could you please help to understand why it is happening?

Command that gave that result:
`.\texture-synthesis.exe --inpaint imgs/masks/nal.jpg --in-size 500 --out-size 500 --tiling -o out/nal_1.jpg generate -- imgs/nal.jpg`

**Comment by anopara** [comment]
Hi Denis! You'd need to use guided synthesis, similar to example 3. At the moment, there is no way to enforce symmetry during synthesis -- a trick around is to generate only half and mirror it later :) 

We also describe this example during [our talk](https://youtu.be/fMbK7PYQux4?t=2059).

**Comment by cfoster0** [comment]
On a related note, how did you handle UV unwrapping for the rock synthesis? The color/displacement maps look like a top-down projection but then the output models have nice overhang and side features.

**Comment by anopara** [comment]
in Houdini, I iteratively relaxed the model while pinning its "borders" to a unit square (min dist projection) to minimize distortion (which is still present, but that's the trade off for keeping the unwrap continuous since texture synthesis currently doesn't support discontinuities).  Probably a similar setup can be achieved directly in UV space!
