### ISSUE TITLE
Pattern Transforms

### ISSUE THREAD

**Issue by lucasdomanico** [EmbarkStudios/texture-synthesis#17]
Hello! First, thanks for this amazing project.
I have a question:
Looking at single example generation, I noticed there are not "transformed" patterns in the generated image.
By transformed I mean, rotation, scale and warping. Of patterns in the example.
Is there a way to achieve this?
Thanks!

**Comment by cfoster0** [comment]
Not one of the authors of this repo but: you could add rotated and/or scaled versions of the example image as additional examples.

**Comment by lucasdomanico** [comment]
Yes, thanks. That is the workaround as a last resort.
But first I would like to know if it is possible using a single example.

**Comment by anopara** [comment]
Hi! As @cfoster0 correctly points out, you can add transformed images as examples. At the moment it is not possible to do with just a single example

**Comment by lucasdomanico** [comment]
Thanks!!
