### ISSUE TITLE
Open source

### ISSUE THREAD

**Issue by Jake-Shadle** [EmbarkStudios/texture-synthesis#2]
Tasks remaining to open source this. A bunch of these steps are listed in more detail on https://github.com/EmbarkStudios/rust-ecosystem/blob/master/open-sourcing.md

First steps: 

- [x] Bring over everything from our Rust template: https://github.com/EmbarkStudios/rust-ecosystem
- [x] Pick and use an emoji for the repo :smile: :art: 
- [x] Make sure crate can be packaged with cargo package
- [x] Bring over README to lib.rs and verify it looks good with cargo doc
- [x] Add Travis CI to the repo
- [x] Remove checked in .exe and replace with CI published GitHub release. Believe @Jake-Shadle has a travis script that does that
- [x] Test switching out and use the crate in our own projects (with file dependency) @Jake-Shadle 
- [x] Team review code & docs

Final steps in-order (after all above are done):

- [x] Publish on crates.io
- [x] Make repo public @repi 
- [x] Switch out to use this crate in our own projects @Jake-Shadle 
- [x] Add to list on http://embark.rs
- [ ] Announce on twitter @anopara 
- [ ] Announce on reddit @anopara

**Comment by repi** [comment]
Repo is public now! Great work @anopara @Jake-Shadle and everyone else that contributed to getting it released!
