### ISSUE TITLE
Suggestion: CLI option to automatically add mirrorings and rotations of input image

### ISSUE THREAD

**Issue by vi** [EmbarkStudios/texture-synthesis#30]
Suggesting to have something like `--fips-and-rotates` option:

    texture-synthesis -o out.png --tiling generate --fips-and-rotates in.png

Which does approximately this:

```
convert in.png -rotate 0 in1.png
convert in.png -rotate 90 in2.png
convert in.png -rotate 180 in3.png
convert in.png -rotate 270 in4.png
convert in.png -rotate 0 -flip in5.png
convert in.png -rotate 90 -flip in6.png
convert in.png -rotate 180 -flip in7.png
convert in.png -rotate 270 -flip in8.png
texture-synthesis -o out.png --tiling generate --fips-and-rotates in*.png
```

**Comment by Jake-Shadle** [comment]
This seems like a cool feature to have for the CLI, but I don't think we're planning on doing this in the short term, but PRs are of course welcome!

**Comment by vi** [comment]
Although there is now the `flip-and-rotate` subcommand, it only works in the most primitive mode (i.e. specify a style and get some picture), not in guided mode.

I expected that `--flips-and-rotates` flag also automatically flipped and rotated the associated `--guide`s in sync with example pictures.
