### ISSUE TITLE
Inpaint error

### ISSUE THREAD

**Issue by JoseConseco** [EmbarkStudios/texture-synthesis#41]
When using example CLI for texture-synthesis: 
 .\texture-synthesis.exe --out-size 400 --inpaint imgs/masks/3_inpaint.jpg -o out/05.png generate imgs/3.jpg
I get error:
[31merror[0m: the input size (0x0) must match the output size (400x400) when using an inpaint mask
But the mask and image and output are same size 400x400.

**Comment by Jake-Shadle** [comment]
This is actually fixed already https://github.com/EmbarkStudios/texture-synthesis/blob/master/CHANGELOG.md#changed we just haven't done a release yet, I will close this issue once we have done so.

For now to workaround this, just specify `--in-size` the same as `--out-size`

**Comment by Jake-Shadle** [comment]
Release [0.6.0](https://github.com/EmbarkStudios/texture-synthesis/releases/tag/0.6.0) contains a change to the CLI for inpaint, when using inpaint, `--out-size` is used to resize inputs in addition to setting the output size due to how inpaint works. When using `--inpaint`, `--in-size` is ignored.
