### ISSUE TITLE
Texture synthesis inpaint - ignores tiling. 

### ISSUE THREAD

**Issue by JoseConseco** [EmbarkStudios/texture-synthesis#42]
Not sure if this is bug but tiling wont work on inpaint  image:
![image](https://user-images.githubusercontent.com/13521338/65378656-ec1f9a80-dcbb-11e9-97dc-c612c2ec400d.png)
I think it would be cool to have this option here too.
And the command I tried:
'C:\\Users\\XXX\\Desktop\\texture-synthesis-0.5.0-x86_64-pc-windows-msvc\\texture-synthesis.exe', '--out', 'C:\\Users\\XXX\\Desktop\\Test\\TileTest\\Free Texture Asphalt_OUT.png', '--out-size', '512x512', '--seed', '1', '--rand-init', '1', '--in-size', '512x512', '--tiling', '--inpaint', 'C:\\Users\\XXX\\Desktop\\Test\\TileTest\\Free Texture Asphalt_inpaint.png', 'generate', 'D:\\TexturyDarmowe\\Droga\\Free Texture Asphalt.jpg'

**Comment by anopara** [comment]
Hi Jose! When doing tiling, your inpaint mask must have some black padding around to indicate that those pixels can be altered :) all white areas will be left as is -- so you are getting an expected behavior!

**Comment by JoseConseco** [comment]
Ok. Thx for info. I just wanted to let you know I made some GUI for TextureSynthesis as addon for Blender:
https://github.com/JoseConseco/texture_synthesis
Thanks for making this great program.
