### ISSUE TITLE
Very long execution time running the examples

### ISSUE THREAD

**Issue by materialjan** [EmbarkStudios/texture-synthesis#56]
Running the given examples take a **lot** more time than using the cli version on the same machine.
`texture-synthesis --out out/01.jpg generate imgs/1.jpg`
took 20 seconds
while 
`cargo run --example 01_single_example_synthesis`
took like 12 minutes with cpu on full throttle.

**Device:**
 - OS: Os X 10.13.6
 - rustc 1.38.0 (625451e37 2019-09-23)
 - Version 0.6.0 master branch freshly compiled today.

Run the example twice after compilation. Same.
Thanks.
jan

**Comment by repi** [comment]
Just using `cargo run` builds and runs the executable in debug mode, which is slow. 

Use: `cargo run --release -- --example 01_single_example_synthesis` to run an optimized release build which is much faster
