### ISSUE TITLE
Please update the addon to also function on macOS and Linux

### ISSUE THREAD

**Issue by robw001** [EmbarkStudios/texture-synthesis#63]
The texture-synthesis executable is available for several platforms, including Windows, macOS and Linux.

At current, the blender addon only works for MS Windows. It specifically looks for "texture-synthesis.exe' and fails to find the macOS executable "texture-synthesis". Please update the addon to include other platforms.

I got the addon to work on macOS by editing addon_preferences.py as follows:

```
import os, platform
(...)

class TextureSynthPreferences(bpy.types.AddonPreferences):
    bl_idname = addon_name_lowercase()

    def check_ts_exist(self, context):
        absPath, ts_exists = check_file_exist(self.text_synth_path)
        self['text_synth_path'] = absPath
        if platform.system() in ["Darwin","Linux"]:
            if ts_exists and os.path.basename(absPath) == "texture-synthesis":
                self.display_info = "texture-synthesis found in: " + absPath
        else:
            if ts_exists and os.path.basename(absPath) == "texture-synthesis.exe":
                self.display_info = "texture-synthesis.exe found in: " + absPath
            else:
                self.display_info = "texture-synthesis.exe not found in: " + absPath

(...)
```

**Comment by repi** [comment]
The blender addon that uses this library is in the https://github.com/JoseConseco/texture_synthesis repository so please do file the issue there. thanks!

**Comment by robw001** [comment]
Thanks, did that.

**Comment by AndreaMonzini** [comment]
You can just renamed the executable binary  `synthesis` to `synthesis.exe` and it works.
