### ISSUE TITLE
Add sample mask example

### ISSUE THREAD

**Issue by Jake-Shadle** [EmbarkStudios/texture-synthesis#86]
Though #85 is a bug in structopt, we should still have at least one example of using sample masks, so that if users copy it and replace eg, the input image paths, they won't get this confusing error message.

**Comment by Jake-Shadle** [comment]
Also need to add a test specifically for sample masks as they don't really have an explicit one at the moment. https://github.com/EmbarkStudios/texture-synthesis/issues/85#issuecomment-569887031

**Comment by Hugo-Trentesaux** [comment]
I wrote this but it seems not to work (runs forever)

```rust
use texture_synthesis as ts;

// painting into the 1.jpg image, with the shape given by 3_inpaint.jpg, using pattern of 2.jpg
fn main() -> Result<(), ts::Error> {
    let texsynth = ts::Session::builder()
        .inpaint_example(
            &"imgs/masks/3_inpaint.jpg",
            ts::Example::builder(&"imgs/1.jpg").set_sample_method(ts::SampleMethod::Ignore),
            ts::Dims::square(400),
        )
        .add_example(ts::Example::builder(&"imgs/2.jpg").set_sample_method(ts::SampleMethod::All))
        .build()?;

    let generated = texsynth.run(None);
    generated.save("out/09.jpg")
}
```

**Comment by Jake-Shadle** [comment]
Fixed by #98

**Comment by Jake-Shadle** [comment]
Oops.

**Comment by Hugo-Trentesaux** [comment]
I think such an example could be added in the README.
I proposed a version here : https://github.com/Hugo-Trentesaux/texture-synthesis#cli-2

**Comment by Jake-Shadle** [comment]
Looks good, feel free to make a PR. :)

**Comment by Hugo-Trentesaux** [comment]
https://github.com/EmbarkStudios/texture-synthesis/pull/112

done ;)
