### ISSUE TITLE
Is a 3d (voxel) version of this tool planned?

### ISSUE THREAD

**Issue by SiebenCorgie** [EmbarkStudios/texture-synthesis#88]
Hi,

I watched the talk linked in the Readme. At the end Anastasia mentions that you are currently working on bringing the 2d concept to 3d.

I am currently working on a (hobby) Voxel enigne in rust+vulkan and thought it might be easy to transfer the algorithm to 3d given a good Voxel loading/editing crate similar to the `image` crate.

Are there already working prototypes internally which take some 3d information and apply the algorithm to generate a new 3d model? Do you have some more crates in this direction planed or would it make sense for me to either extent this project to also worke in 3d or create a new one from scratch?

Greetings
Tendsin Mende

**Comment by repi** [comment]
No current plans to extend this crate to 3D, it would likely have to work quite differently and with very different types of source material. So think if one would explore more 3d volume synthesis it would be easiest to do that as separate crate(s).
