### ISSUE TITLE
Make a release!

### ISSUE THREAD

**Issue by Jake-Shadle** [EmbarkStudios/texture-synthesis#97]
We've had some really nice performance improvements landed thanks to @Mr4k that should be released, but I haven't had time this week to finish up some lingering issues that should also be in the release.

- [ ] - ~#89~ (cutting this because we can refactor the docs separately from releasing)
- [x] - #38 
- [x] - #86

**Comment by repi** [comment]
Also want the upgrade to `image` 0.23 in a new release (#105)

**Comment by Jake-Shadle** [comment]
![](https://media.giphy.com/media/mcbCGDQxefpfO/giphy.gif)
